name: Bug Report
description: Report a reproducible bug in tsk
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue.
        Please provide enough detail so we can reproduce and fix it quickly.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Include expected behavior and actual behavior.
      placeholder: Clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run `tsk ...`
        2. Press `...`
        3. Observe `...`
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: tsk version
      placeholder: e.g. 0.2.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g. macOS 15.3 / Ubuntu 24.04
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant output. Remove secrets/tokens before submitting.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checks
      options:
        - label: I searched for existing issues that describe this problem.
          required: true
        - label: I removed secrets and sensitive data from logs.
          required: true
